### ISSUE TITLE
Downloading certain data models not working

### ISSUE THREAD

**Issue by ashvsdata** [mdda/deep-learning-workshop#2]
--2016-07-30 13:55:42--  http://sydney.edu.au/engineering/it/~matty/Shakespeare/shakespeare.tar.gz
Resolving sydney.edu.au... 129.78.5.8
Connecting to sydney.edu.au|129.78.5.8|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-07-30 13:55:47 ERROR 404: Not Found.
- '[' '!' -e ALL_1-vocab.txt.gz ']'
- gzip ALL_1-vocab.txt
  gzip: can't stat: ALL_1-vocab.txt (ALL_1-vocab.txt): No such file or directory

Thanks 
~ashwin

**Comment by mdda** [comment]
I've updated the download location for the shakespeare to match your fork.  I've also uploaded ALL_1-vocab.txt it to RedCatLabs.com - and added logic to `2-get-data-and-models.bash`.
